### ISSUE TITLE
EnhancedRouter with nested routes

### ISSUE THREAD

**Issue by BotellaA** [vuchan/vue-mfe#2]
I would like to use your `EnhancedRouter` with nested routes. How should I proceed?

I tried this but it does not do anything.
```
      const routerHelpers = createEnhancedRouter(router);
      routerHelpers.addRoutes([{path: "foo"}], "/home/bar");
```
Thanks for your help

**Comment by givingwu** [comment]
1. Hope this reply is not too late, if it be i am very sorry And i will open the notification of the Github emails.

2. I wanna say that `vue-mfe` is not a repo for `nested routes`, and the native vue-router is good enough for that. `vue-mfe` was designed for dynamic routes injection to lazy load a child Application. 

3. The main method `addRoutes` in `EnhancedRouter` class is [right here](https://github.com/vuchan/vue-mfe/blob/master/src/helpers/EnhancedRouter.js#L59), and your code usage on the right way i think, did anything goes wrong?

i think i do not understand what is the real problem on your question by the given ISSUE text.

**Comment by givingwu** [comment]
Thanks for your issue. @BotellaA, I rewrote the core API and only exposed only Three api now.

1. `VueMfe.createApp`
2. `VueMfe.createSupApp`
3. `VueMfe.Lazy`

You can see more details in the new README.md.
